---
title: "CV"
output: 
  html_document:
    toc: true
    toc_float: true
---
### Education	
<p>
University of Rochester	Rochester, NY <span style ="float:right">September 2004-May 2008 </span>  <br>
Bachelor of Science, Biomedical Engineering	<br>
* Concentration: Cell and Tissue Engineering
<br></p>

### Laboratory Experience

Columbia University Mailman School of Public Health	New York,NY<br>
Center for Infection and Immunity	<br>
* Staff Associate             <span style ="float:right">June 2016 - Present</span>
<br>
* Technician B <span style ="float:right">Jan 2010 - June 2016</span><br>
* Technician A <span style ="float:right">April 2009 - Jan 2010</span><br>

### Laboratory Skills	
<p>
Nucleic acid extraction from various tissue types and cDNA synthesis <br>
PCR, SDS-PAGE and agarose gels<br>
Purification of PCR products and proteins<br>
Molecular Cloning<br>
In-Situ hybridization/Immunohistochemistry<br>
LIPS (Luciferase Immunoprecipitation) Assay<br>
Western, Southern, and Northern Blot<br>
Transfections of cells with PCR generated constructs<br>
Maintenance and oversight of the UGenius gel imager and UV boxes<br>
Maintenance and operational oversight of the easyMAG nucleic acid extraction machine<br>
Maintenance and operational oversight of the BDMax<br>
Laboratory waste management<br>
Able to write standard operating procedures <br>
Able to use Geneious for genomic sequence analysis and primer design<br>
BSL-3 access and Select Agents Program Approval<br>
</p> 
### Projects	

<p>Acute Encephalitis Syndrome (AES) outbreak in the Uttar Pradesh province of India <span style=" float:right"> (2017-present) </span> <br> </p> 
* Process samples on site in Gorakhpur India for molecular and serological tests<br>
* Analyzed sequencing data to identify pathogenic agents that may be a probable cause of AES<br>
* Analyze serological data to determine positive and negative thresholds for probably agents and define samples as positive or negative for said agent<br>
* Analyze collected data to find links between case outcomes, molecular data and serological data<br>

<p>CII ArboViroPlex Assay FDA EUA  <span style="float:right"> (2016-2017) </span> <br> </p> 
* Develop, multiplex and optimization of an RTqPCR assay to accurately detect Zika virus, Dengue virus, West Nile virus and Chikungunya virus<br>
* Generate RNA constructs for standards<br>
* Grow and extract cell culture supernatants for limit of detection tests<br>
* Help write up and submit an FDA EUA <br>
* Process FDA packet to validate assay with samples which we did not know what the results should be.<br>

<p>MERS Surveillance of Camels in Riyahd, Saudi Arabia <span style="float:right">(August 2016)	</span> <br> </p>
* Extract several hundred samples in two weeks on location in Riyahd, Saudi Arabia
* Process samples for RTqPCR in duplicates.
* Record results and send to supervisor for final analysis

<p>Pathology of Diseased Tilapia with unknown infectious agent <span style="float:right">(2015-2016)</span> <br> </p>
* Preparation of samples for unbiased HTS
* Analysis of HTS data to identify and sequence infectious agent
* Designing constructs for northern blot assay
* In-situ hybridization of paraffin embedded slides using probes designed from HTS data

<p>West African Multiplex Assay <span style="float:right"> (2014-2015) </span> <br> </p>
* Testing multiplex PCR assay mixes on the BD Max machine
* Testing compatibility of various sample types on the BD Max machine
* Program adjustments to optimize signal output 
 
<p> Pathogen burden of Rats in NYC <span style="float:right"> (2013-2014) </span> <br> </p>
* Extraction of various tissue types and prepping samples for unbiased high-throughput sequencing 
* Analyzing high-throughput data
 

### Publications	

Nischay Mishra; Shamsudeen F. Fagbo; Abdulaziz N. Alagaili; Adam Nitido; Simon H Williams; James Ng; Bohyun Lee; Abdulkareem Durosinloun; Joel A Garcia; Komal Jain; Vishal Kapoor; Jon H Epstein; Thomas Briese; Ziad A Memish; Kevin J Olival; W Ian Lipkin. A viral metagenomic survey identifies known and novel mammalian viruses in bats from Saudi Arabia. PLOS ONE (in-press) 09/2018. 
 
Thiago Souza, Yasmine Rangel Vieira, Edson Delatorre, Giselle Barbosa-Lima, Raul Leal Faria Luiz, Alexandre Vizzoni, Komal Jain, Milene Mesquita, Nishit Bhuva, Jan F. Gogarten, James Ng, Riddhi Thakkar, Andrea Surrage Calheiros, Ana Paula Teixeira Monteiro, Patricia T Bozza, Fernando A Bozza, Diogo A Tschoeke, Luciana Leomil, Marcos Cesar Lima de Mendonca, Cintia Damasceno dos Santos Rodrigues, Maria C Torres, Ana Maria Bispo de Filippis, Rita Maria Ribeiro Nogueira, Fabiano L. Thompson, Cristina Lemos, Betina Durovni, Jose Cerbino-Neto, Carlos M Morel, Ian Lipkin, Nischay Mishra. Emergence of the East-Central-South-African genotype of Chikungunya virus in Brazil and the city of Rio de Janeiro may have occurred years before surveillance detection. 21 Dec 2018, bioRxiv, doi: https://doi.org/10.1101/502443.

Mishra N, Caciula A, Price A, Thakkar R, Ng J, Chauhan L. V, Jain K, Che X, Espinosa D. A, Montoya Cruz M, Balmaseda A, Sullivan E. H, Patel  J. J, Jarman R. G, Rakeman J. L, Egan C. T, Reusken C, Koopmans M, Harris E, Tokarz R, Briese T, Lipkin W. I. (2018). Diagnosis of Zika Virus Infection by Peptide Array and Enzyme-Linked Immunosorbent Assay. mBio, 9(2), e00095-18. doi:10.1128/mBio.00095-18

Bacharach E, Mishra N, Briese T, Zody MC, Kembou Tsofack JE, Zamostiano R, Berkowitz A, Ng J, Nitido A, Corvelo A, Toussaint NC, Abel Nielsen SC, Hornig M, Del Pozo J, Bloom T, Ferguson H, Eldar A, Lipkin WI. Characterization of a Novel Orthomyxo-like Virus Causing Mass Die-Offs of Tilapia. MBio. 2016 Apr 5;7(2). pii: e00431-16. doi: 10.1128/mBio.00431-16

Firth C, Bhat M, Firth MA, Williams SH, Frye MJ, Simmonds P, Conte JM, Ng J, Garcia J, Bhuva NP, Lee B, Che X, Quan PL, Lipkin WI. Detection of zoonotic pathogens and characterization of novel viruses carried by commensal Rattus norvegicus in New York City. MBio. 2014 Oct 14;5(5):e01933-14. doi: 10.1128/mBio.01933-14 

### Other Skills
•	Able to use Microsoft Office including Microsoft Word, Microsoft Power Point, Microsoft Excel and Microsoft Outlook
	•	Able to use Adobe Photoshop 
	•	Able to analyze, prepare and present data to peers
	•	Fluent In Cantonese
	•	Able to input data into LIMS 
	•	Basic coding in RStudio

### Certificates
•	Blood borne pathogen safety
	•	Laboratory Hazardous Waste Safety
	•	Use of Formaldehyde safety
	•	Recombinant DNA training
	•	Biosafety Viral vector training
	•	HIPAA training
	•	Human subjects protection training 
 
### References
References available upon request




