---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
set.seed(1)

data(nyc_airbnb)
nyc_abnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Bronx"
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_abnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_abnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

### Chart C

```{r}
data("rest_inspec")

bx_rest=rest_inspec %>% 
  filter(
    boro=="BRONX",
    cuisine_description="Chinese") %>% 
  mutate(
    total=fct_reorder()
  )
  
bx_rest %>% 
  ggplot(aes(x=cuisine_description,y=total))+
  geom_col()+
  coord_flip(xlim = NULL, ylim = NULL, expand = TRUE, clip = "on")
bx_rest %>% 
  plot_ly(
    x = ~cuisine_description, y = ~total, type = "bar", mode = "markers",
    color = ~total, text = ~cuisine_description, alpha = 0.5)
```

